# Generated by Django 5.2.1 on 2025-06-10 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('man', 'man'), ('woman', 'woman'), ('child', 'child')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Box',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('black', 'black'), ('white', 'white'), ('blue', 'blue'), ('beige', 'beige')])),
                ('brice_before', models.IntegerField(blank=True, null=True)),
                ('description', models.TextField(max_length=1000)),
                ('size', models.CharField(choices=[('S', 'S'), ('L', 'L'), ('XL', 'XL'), ('M', 'M')], max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='back_library')),
                ('price', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('available', 'Available'), ('sold', 'Sold')], max_length=10, null=True)),
                ('active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='my_ecom.category')),
            ],
        ),
    ]
