# Generated by Django 5.2.1 on 2025-06-10 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_ecom', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='box',
            name='pages',
        ),
        migrations.AddField(
            model_name='box',
            name='cloths',
            field=models.CharField(choices=[('Tshirt', 'Tshirt'), ('pants', 'pants'), ('jacket', 'jacket'), ('shoes', 'shoes'), ('blouse', 'blouse')], default='Tshirt', max_length=50),
        ),
    ]
