# Generated by Django 5.2.1 on 2025-06-10 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_ecom', '0002_remove_box_pages_box_cloths'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='eback'),
        ),
    ]
