# Generated by Django 5.2.1 on 2025-06-10 23:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_ecom', '0003_alter_box_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='box',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_ecom.category'),
        ),
    ]
