# Generated by Django 5.2.3 on 2025-06-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_ecom', '0004_alter_box_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catcloth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.CharField(choices=[('Tshirt', 'Tshirt'), ('pants', 'pants'), ('jacket', 'jacket'), ('shoes', 'shoes'), ('blouse', 'blouse')], max_length=100)),
            ],
        ),
    ]
